### ISSUE TITLE
Add support for Renv

### ISSUE THREAD

**Issue by jerowe** [anyenv/anyenv#21]
This is a feature request for additional support.

Renv is a rbenv like version manager for R. https://cran.r-project.org/

https://github.com/viking/Renv
https://github.com/viking/R-build

Thanks for the great tool! ;)

**Comment by riywo** [comment]
Hi @jerowe,

Thank you for the request. Creating a pull request is very easy for everyone. Could you create a PR?

See https://github.com/riywo/anyenv/pull/20

Best,
riywo

**Comment by riywo** [comment]
Already done. https://github.com/riywo/anyenv/pull/17
