### ISSUE TITLE
Why is there not uninstall subcommand?

### ISSUE THREAD

**Issue by mizunashi-mana** [anyenv/anyenv#28]
I want uninstall.  But, `anyenv` seems to have no uninstall subcommand.  I use `rm -rf ~/.anyenv/envs/[target env]`.

I will be glad to add `uninstall`.  It seem to be very easy for me.
Are there any problems for `uninstall`?

**Comment by riywo** [comment]
Thanks. I've added the uninstall subcommand.

**Comment by mizunashi-mana** [comment]
Thanks!
