### ISSUE TITLE
Silent error occurs in 'eval "$(anyenv init -)"'

### ISSUE THREAD

**Issue by ryym** [anyenv/anyenv#32]
Currently, [the `anyenv-init` executes `**env-init` scripts](https://github.com/riywo/anyenv/blob/ed02e3b1c0e5ad684ae458c8c212bfbeda8bbe85/libexec/anyenv-init#L107) before it adds `**env/bin` to the `$PATH`. But it causes an error because each `**env-init` script assumes the `**env` command is in the `$PATH` when it is called and runs the command directly in the script (e.g. [rbenv](https://github.com/rbenv/rbenv/blob/29b4da77370af0a3413dce00a72c7631302a2b25/libexec/rbenv-init#L107)).

The following Bash script can reproduce the error.

``` bash
#!/usr/bin/env bash

xxENV='rbenv'  # goenv, ndenv, luaenv, ...

ANYENV_PATH=$HOME/.anyenv

# Ensure '$xxENV' command is not in the '$PATH'.
export PATH="$ANYENV_PATH/bin":/usr/local/bin:/usr/bin:/bin

# rm -rf "$ANYENV_PATH"
git clone https://github.com/riywo/anyenv "$ANYENV_PATH"
[ $? -ne 0 ] && exit 1

eval "$(anyenv init -)"

anyenv install $xxENV

set -ex
trap 'echo "======= ERROR! ======="' ERR

# Initialize to enable 'xxenv' commands.
eval "$(anyenv init -)"  # XXX: ERROR

# Unreachable
set +ex
echo 'anyenv-init finished successfully!'
```

My environment:
- Mac OS X EI Capitan
- GNU bash version 3.2

**Comment by riywo** [comment]
Thanks!
