### ISSUE TITLE
Suggestion: deprecate nenv and ndenv

### ISSUE THREAD

**Issue by mizunashi-mana** [anyenv/anyenv#38]
This repository supports `nodenv`, `nenv` and `ndenv`, node version managers.

`anyenv` seems to recommend to use `ndenv`.
However, `nodenv` has more plugins and more supports.
Especially, `node-build` for `ndenv` has no longer mainteinance, but one for `nodenv` is maintaining.

All managers for programming languages on `anyenv` are only one except for `node`.
But, there are three managers for `node`.

I think this is not desirable thing for node user.

**Comment by riywo** [comment]
I'm going to remove `ndenv` and `nenv` for the default manifests of the new anyenv: https://github.com/anyenv/anyenv-install

In the near future, this repository will be redirected to the new one.
