### ISSUE TITLE
chruby

### ISSUE THREAD

**Issue by mcandre** [anyenv/anyenv#39]
Please add support for chruby, a tool that integrates with rvm in order to switch Ruby versions on a dotfile, per-directory basis.

https://github.com/postmodern/chruby

**Comment by ndxbn** [comment]
chruby requries `sudo` to install, so anyenv may not be able to support chruby.

**Comment by riywo** [comment]
We already have `rbenv`.

In the new [anyenv/anyenv](https://github.com/anyenv/anyenv), you can easily write your own manifest.
