### ISSUE TITLE
jenv.io

### ISSUE THREAD

**Issue by mcandre** [anyenv/anyenv#40]
Please support jenv.io, a variant of jenv that integrates with IntelliJ, and manages versions for Java build tools (Maven, Gradle, SBT). If necessary, move the current "jenv" to "jenv.be".

**Comment by BrianHawley** [comment]
The current jenv is the jenv.be one, for what it's worth.

**Comment by riywo** [comment]
In the new [anyenv/anyenv](https://github.com/anyenv/anyenv), you can easily write your own manifest.
