### ISSUE TITLE
Option to install additional plugin to *env

### ISSUE THREAD

**Issue by z0rc** [anyenv/anyenv#45]
Right now anyenv defines list of plugins installed with *env. I'd like to have an option to install additional plugins for existing *env.

**Comment by riywo** [comment]
Hi,

I'm considering about splitting anyenv itself and env/plugin list. I'd like to hear your opinions against this idea at #46

Best,

**Comment by riywo** [comment]
In the new [anyenv/anyenv](https://github.com/anyenv/anyenv), you can easily write your own manifest.
