### ISSUE TITLE
Externalize env/plugin list

### ISSUE THREAD

**Issue by riywo** [anyenv/anyenv#46]
I'm considering about splitting anyenv itself and env/plugin list. So far this repository consists both of them and the env/plugin list is a kind of recommendation, then this repository has to be kept updated.

If you can specify your own list outside this repository and share the list, you and your team can customize the catalog of env/plugin without modifying this repository.

Here are the images:

```
$ ls ~/.anyenv-config/
pyenv    rbenv

$ cat ~/.anyenv-config/rbenv
install_env "https://github.com/rbenv/rbenv.git" "master"
install_plugin "ruby-build" "https://github.com/rbenv/ruby-build.git" "master"

$ anyenv install -l
Available **envs:
  pyenv
  rbenv    
```

**Comment by riywo** [comment]
Any thoughts?

**Comment by z0rc** [comment]
This looks good for me. But I'd really like to see that `~/.anyenv-config` path is replaced by `$XDG_CONFIG_HOME/anyenv` or `~/.config/anyenv` if `XDG_CONFIG_HOME` is not set. Please don't pollute our `$HOME`s with unnecessary top level dotfiles. XDG spec is more than a decade old, we really should follow it. Even on servers, there are lots of applications that follow this spec, like `systemd`, `mc`, `htop`, `git` and so on.

**Comment by z0rc** [comment]
On the second thought, I believe user needs a template, default config, or samples to build his/her own config. Probably this can be covered as a documentation.

**Comment by minhoryang** [comment]
totally agreed with @z0rc

**Comment by minhoryang** [comment]
ping?

**Comment by riywo** [comment]
I feel it is almost ready to use as beta. Please provide any feedback!

https://github.com/anyenv/anyenv

**Comment by riywo** [comment]
Basic implementation is completed. Please provide feedback!
