### ISSUE TITLE
zsh completions are weird (tested with `rbenv` and `pyenv`)

### ISSUE THREAD

**Issue by ericmarkmartin** [anyenv/anyenv#54]
I noticed that while completions are fine when just typing `pyenv` or `rbenv` and hitting tab, when I try to do it with a subcommand I get
```
rbenv install Usage: rbenv completions <command> [arg1 arg2...]
Usage: rbenv completions <command> [arg1 arg2...]
Usage: rbenv completions <command> [arg1 arg2...]
```

or with pyenv 
```
pyenv install Usage: pyenv completions <command> [arg1 arg2...]
Usage: pyenv completions <command> [arg1 arg2...]
Usage: pyenv completions <command> [arg1 arg2...]
```

but it works with `pyenv` (or `rbenv`, but I'm just gonna paste `pyenv` because it's essentially the same thing) just installed through brew
```
pyenv shell
--help   --unset  3.6.2    system 
```

Note: I am using `zsh` and `prezto`.

**Comment by riywo** [comment]
I've never seen this before.

Feel free to reopen this with reproducing steps.
