### ISSUE TITLE
Support read-only ${ANYENV_ROOT}

### ISSUE THREAD

**Issue by czchen** [anyenv/anyenv#55]
I am currently working on [creating official package for anyenv](https://bugs.debian.org/874030). However, since anyenv uses `ANYENV_ROOT` for both its code and download content, I cannot put anyenv in read-only directory (e.g. `/usr/share/anyenv`) and let other user download **env to their directory (e.g. `~/.anyenv). It would be better if anyenv can be in a read-only directory and all download content can be in another read-write directory.

**Comment by riywo** [comment]
Could you provide more use cases? How do you want to bake `envs` directory? And do you want to allow users to install envs/versions as well?

Feel free to reopen this issue.
