### ISSUE TITLE
Please support rust

### ISSUE THREAD

**Issue by isuke** [anyenv/anyenv#60]
I love anyenv.
This is very useful library.

I want to support rust.
rust version manager is [rsvm](https://github.com/sdepold/rsvm) or [rustup](https://github.com/rust-lang-nursery/rustup.rs).

Thank you.

**Comment by riywo** [comment]
In the new [anyenv/anyenv](https://github.com/anyenv/anyenv), you can easily write your own manifest.

**Comment by isuke** [comment]
Thank you very much :)
