### ISSUE TITLE
homebrew support

### ISSUE THREAD

**Issue by jkthorne** [anyenv/anyenv#63]
seems like someone opened this PR. https://github.com/Homebrew/homebrew-core/pull/15912

Is there any way to get this merged?
I cannot comment on the thread.

**Comment by kevinelliott** [comment]
I'd like to see this supported as well.

**Comment by riywo** [comment]
I'm going to support this feature in the new repository. https://github.com/anyenv/anyenv/issues/1

**Comment by kevinelliott** [comment]
@riywo I'm a little confused by the reference you linked in your last comment. Going there shows the same repository but an issue that is from 2013. Is this in error?

**Comment by riywo** [comment]
The repository has been transferred. Also, it is finally supported by Homebrew right now. You can install by `brew install anyenv`

**Comment by kevinelliott** [comment]
@riywo Transfered to where? Thanks, btw.

**Comment by riywo** [comment]
from `riywo/anyenv` to `anyenv/anyenv`. All traffic to `riywo/anyenv` is redirected to `anyenv/anyenv` now, so you saw the same repository.
