### ISSUE TITLE
mac os mojave

### ISSUE THREAD

**Issue by 75asa** [anyenv/anyenv#64]
can't build path...
after install, i typed `which anyenv`.
but it just showed some script.
can't use phpenv, rbenv, pyenv so anyenv. 
plz help me.

**Comment by 75asa** [comment]
```
anyenv () {
	typeset command
	command="$1"
	if [ "$#" -gt 0 ]
	then
		shift
	fi
	command anyenv "$command" "$@"
}
```

**Comment by 75asa** [comment]
↑the sentences when I typed `which anyenv` !

**Comment by riywo** [comment]
It is normal behaviour. Why do you execute `which anyenv` rather than `anyenv`?

Feel free to reopen this issue.

**Comment by 75asa** [comment]
返信ありがとうございます。
経緯としては、anyenv導入後、切り替えた筈のverが通っておらず、anyenv自体は通っているのかと確認したことがきっかけです。
その後、他のenv系が原因の１つであるとわかり、一旦アンインストールしたのちにanyenvを導入したところ使えるようにはなりました！
がwhichでは未だ上記のスクリプトが出現する次第です....
