### ISSUE TITLE
Install anyenv doesn't work on fish shell

### ISSUE THREAD

**Issue by thalathalaylah** [anyenv/anyenv#69]
On fish shell,  I get error output when installing anyenv by Manual git checkout.
(for fish shell, I replace `~/.your_profile` with `~/.config/fish/config.fish`)
```
$ git clone https://github.com/anyenv/anyenv ~/.anyenv
$ echo 'export PATH="$HOME/.anyenv/bin:$PATH"' >> ~/.config/fish/config.fish
$ echo 'eval "$(anyenv init -)"' >> ~/.config/fish/config.fish
$ exec fish -l
~/.config/fish/config.fish (line 2): $(...) is not supported. In fish, please use '(anyenv)'.
eval "$(anyenv init -)"
      ^
from sourcing file ~/.config/fish/config.fish
	called during startup

source: Error while reading file '/home/test/.config/fish/config.fish'
```
This error is due to a difference of fish commands and other shells commands.

The following code worked.
(I replaced `eval "$(anyenv init -)"` with `source (anyenv init - fish|psub)` and `export PATH="$HOME/.anyenv/bin:$PATH"` with `set -gx PATH $HOME/.anyenv/bin $PATH`)
```
$ git clone https://github.com/anyenv/anyenv ~/.anyenv
$ echo 'set -gx PATH $HOME/.anyenv/bin $PATH' >> ~/.config/fish/config.fish
$ echo 'source (anyenv init - fish|psub)' >> ~/.config/fish/config.fish
$ exec fish -l
```

So I want to add description in README like https://github.com/anyenv/anyenv/pull/67

**Comment by riywo** [comment]
Thank you for your report. I’ll try to update as rbenv does.

I personally don’t use fish, so patches are welcome. You or other fish users must be smarter than me.
