### ISSUE TITLE
tfenv subcommand missing

### ISSUE THREAD

**Issue by gousern** [anyenv/anyenv#79]
Hi. 

Thank you for this good project, it saved me tons of time.

I am using fish shell and tfenv installed. When I open shell, and it shows below message .. 
--
no such command 'init'
Usage: tfenv <command> [<options>]

Commands:
   install       Install a specific version of Terraform
   use           Switch a version to use
   uninstall     Uninstall a specific version of Terraform
   list          List all installed versions
   list-remote   List all installable versions

Welcome to fish, the friendly interactive shell
--
c@mpb ~> anyenv versions
goenv:
Warning: no Go detected on the system

nodenv:
Warning: no Node detected on the system

pyenv:
  system
* miniconda-latest (set by /Users/c/.anyenv/envs/pyenv/version)
swiftenv:
* system
tfenv:
no such command 'versions'
Usage: tfenv <command> [<options>]

Commands:
   install       Install a specific version of Terraform
   use           Switch a version to use
   uninstall     Uninstall a specific version of Terraform
   list          List all installed versions
   list-remote   List all installable versions
--
It seems tfenv using different subcommands.

**Comment by riywo** [comment]
At least `init` should be solved by #82
