### ISSUE TITLE
goenv install command cant use. "goenv: no such command 'install'"

### ISSUE THREAD

**Issue by 2357gi** [anyenv/anyenv#83]
install goenv and do `$goenv install -l`,
go env say `goenv: no such command 'install`.

so i tried this and its work.
`sh ~/.anyenv/envs/goenv/plugins/go-build/install.sh`

The same thing was reproduced in other env.

anyenv: 1.1.1
zsh: zsh 5.3 (x86_64-apple-darwin18.0)

**Comment by riywo** [comment]
I can't reproduce this with https://github.com/syndbg/goenv
