### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by lucas1** [anyenv/anyenv#84]
I'm using Ubuntu-Mate 20.04

after install anyenv and plenv, see error:
$ plenv

Command 'plenv' not found, did you mean:

**Comment by lucas1** [comment]
$ anyenv versions
plenv:
/home/lucas/.anyenv/libexec/anyenv-versions: line 15: plenv: command not found

rbenv:
/home/lucas/.anyenv/libexec/anyenv-versions: line 15: rbenv: command not found

**Comment by riywo** [comment]
Need more info such as `env` output.
