### ISSUE TITLE
path warning in zsh with prezto

### ISSUE THREAD

**Issue by yechentide** [anyenv/anyenv#89]
I get this warning after updating pyenv using `anyenv update`.
There is a [closed issue](https://github.com/pyenv/pyenv/issues/1906) in pyenv repository that explains this warning.

As `pyenv init` says, the solution is:
```shell
# Load pyenv automatically by appending
# the following to ~/.zshrc:

eval "$(pyenv init -)"

# And the following to ~/.profile:

eval "$(pyenv init --path)"

# Make sure to restart your entire logon session
# for changes to ~/.profile to take effect.
```

I am using zsh with prezto, and I don't have `~/.profile`.
I specified the pyenv path manually now, but when I run a new shell I still get the warning.
Can someone help me turn off this warning?

**Comment by yechentide** [comment]
my `~/.zshrc`:

```shell
eval "$(anyenv init -)"
export PATH="/Users/{User}/.anyenv/envs/pyenv/shims:$PATH"
```

the warning I got:

```shell
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```

and my `PATH` variable:

```shell
❯  echo $PATH | tr ':' '\n'
/Users/yechentide/.anyenv/envs/pyenv/shims
/Users/yechentide/.anyenv/envs/swiftenv/shims
/Users/yechentide/.anyenv/envs/swiftenv/bin
/Users/yechentide/.anyenv/envs/rbenv/shims
/Users/yechentide/.anyenv/envs/rbenv/bin
/Users/yechentide/.anyenv/envs/pyenv/bin
/Users/yechentide/.anyenv/envs/nodenv/shims
/Users/yechentide/.anyenv/envs/nodenv/bin
/Users/yechentide/.anyenv/envs/jenv/shims
/Users/yechentide/.anyenv/envs/jenv/bin
/Users/yechentide/.anyenv/envs/goenv/shims
/Users/yechentide/.anyenv/envs/goenv/bin
/usr/local/bin
/usr/local/sbin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by yechentide** [comment]
my environment:

- MacOS 10.15.7
- zsh + prezto

my `~/.zshrc`:

```shell
eval "$(anyenv init -)"
export PATH="/Users/{User}/.anyenv/envs/pyenv/shims:$PATH"
```

the warning I got:

```shell
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```

and my `PATH` variable:

```shell
❯  echo $PATH | tr ':' '\n'
/Users/{User}/.anyenv/envs/pyenv/shims
/Users/{User}/.anyenv/envs/rbenv/shims
/Users/{User}/.anyenv/envs/rbenv/bin
/Users/{User}/.anyenv/envs/pyenv/bin
/usr/local/bin
/usr/local/sbin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by ggicci** [comment]
Use

```shell
eval "$( pyenv init --path )"
eval "$( pyenv init - )"
```

to turn off the warning.

The changes were introduced in https://github.com/pyenv/pyenv/pull/1898. Which pulled the function of manipulating `PATH` out of the original statement `pyenv init -` into `pyenv init --path`.

**Comment by yechentide** [comment]
Thank you for your reply.
I don't know where to set `eval "$( pyenv init --path )"`.
I need to set `eval "$( pyenv init --path )"` in `.profile`, but I don't have such a file.
The following is files in my home directory.

```shell
.zlogin -> /Users/{User}/.zprezto/runcoms/zlogin
.zlogout -> /Users/{User}/.zprezto/runcoms/zlogout
.zpreztorc -> /Users/{User}/.zprezto/runcoms/zpreztorc
.zprofile -> /Users/{User}/.zprezto/runcoms/zprofile
.zsh_history
.zshenv -> /Users/{User}/.zprezto/runcoms/zshenv
.zshrc -> /Users/{User}/.zprezto/runcoms/zshrc
```

I tried to add `eval "$( pyenv init --path )"` into .zprofile and .zlogin, but it didn't work.

**Comment by yechentide** [comment]
Thank you for your reply.
I don't know where to set `eval "$( pyenv init --path )"`.
I need to set `eval "$( pyenv init --path )"` in `.profile`, but I don't have such a file.
The following is files in my home directory.

```shell
.zlogin -> /Users/{User}/.zprezto/runcoms/zlogin
.zlogout -> /Users/{User}/.zprezto/runcoms/zlogout
.zpreztorc -> /Users/{User}/.zprezto/runcoms/zpreztorc
.zprofile -> /Users/{User}/.zprezto/runcoms/zprofile
.zsh_history
.zshenv -> /Users/{User}/.zprezto/runcoms/zshenv
.zshrc -> /Users/{User}/.zprezto/runcoms/zshrc
```

I tried to add `eval "$( pyenv init --path )"` to .zprofile and .zlogin, but it didn't work.

**Comment by yechentide** [comment]
I noticed that I forgot to set the `PYENV_ROOT` variable in `.zprofile`.
Now the warning disappeared, but another problem is that the path for `pyenv/bin` twice.

```shell
❯  echo $PATH | tr ':' '\n'
/Users/{User}/.anyenv/envs/rbenv/shims
/Users/{User}/.anyenv/envs/rbenv/bin
/Users/{User}/.anyenv/envs/pyenv/bin
/Users/{User}/.anyenv/envs/nodenv/shims
/Users/{User}/.anyenv/envs/nodenv/bin
/Users/{User}/.anyenv/envs/pyenv/shims
/Users/{User}/.anyenv/envs/pyenv/bin
/usr/local/bin
/usr/local/sbin
/usr/bin
/bin
/usr/sbin
/sbin
/Library/Apple/usr/bin
```

.zshrc
```shell
eval "$(anyenv init -)"
```

.zprofile
```shell
export PYENV_ROOT="$HOME/.anyenv/envs/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

**Comment by riywo** [comment]
Not sure about the detail, but I think I fixed the `pyenv` issue by https://github.com/anyenv/anyenv/pull/92

Let me know if you're still having an issue.
