### ISSUE TITLE
support pyenv init --path

### ISSUE THREAD

**Issue by iyuuya** [anyenv/anyenv#90]
pyenv settings changed.
maybe since https://github.com/pyenv/pyenv/pull/1898

```
$ pyenv init --path
export PATH="/path/to/.anyenv/envs/pyenv/shims:${PATH}"
```

```
$ pyenv init -
echo 'WARNING: `pyenv init -` no longer sets PATH.'
echo 'Run `pyenv init` to see the necessary changes to make to your configuration.'
export PYENV_SHELL=zsh
source '/path/to/.anyenv/envs/pyenv/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")"
    ;;
  *)
    command pyenv "$command" "$@"
    ;;
  esac
}
```

so it seems that individual measures are required.
around here.
https://github.com/anyenv/anyenv/blob/67d402f08b4f207a10aaac4c1e581ff921d96e76/libexec/anyenv-init#L126-L146

I'm always grateful for anyenv. :heart:
thx.

**Comment by JuPlutonic** [comment]
I don't understand the issue's topic. I have tested [docker](https://gist.github.com/JuPlutonic/004879c3521a8cb246d9dcff5addedea) with anyenv/pyenv and all working great (e.g. pip eggs installation) :
```bash
docker run -it --rm -P 35cb09fc70a2 /bin/zsh                                                                                                                                                                             

:ffffffffffff%  which -a python3
/home/dockerhera/.anyenv/envs/pyenv/shims/python3
/home/linuxbrew/.linuxbrew/bin/python3
/usr/bin/python3
:ffffffffffff% pyenv init --path
export PATH="/home/dockerhera/.anyenv/envs/pyenv/shims:${PATH}"
:ffffffffffff% pyenv init -
export PYENV_SHELL=zsh
source '/home/dockerhera/.anyenv/envs/pyenv/libexec/../completions/pyenv.zsh'
command pyenv rehash 2>/dev/null
pyenv() {
  local command
  command="${1:-}"
  if [ "$#" -gt 0 ]; then
    shift
  fi

  case "$command" in
  rehash|shell)
    eval "$(pyenv "sh-$command" "$@")"
    ;;
  *)
    command pyenv "$command" "$@"
    ;;
  esac
}
:ffffffffffff% anyenv init --path 
# Load anyenv automatically by adding
# the following to your profile:

eval "$(anyenv init -)"
```

**Comment by rcglenn** [comment]
Same thing happening to me using a fresh macos big sur installation, and installing anyenv + pyenv.

**Comment by rcglenn** [comment]
As a workaround I modified the `anyenv-init` script and it looks like it's working again. The modified code is:

```
  if { ${ENV_ROOT}/bin/${env} commands | grep -q '^init$' ; } 2> /dev/null  ; then
    case "$env" in
        pyenv )
            echo "$(${ENV_ROOT}/bin/${env} init --path ${no_rehash_arg}${shell})"
            ;;
        * )
            echo "$(${ENV_ROOT}/bin/${env} init - ${no_rehash_arg}${shell})"
            ;;
    esac
  fi
```

**Comment by peterleif** [comment]
I have the same problem.
There was a change in pyenv since https://github.com/pyenv/pyenv/pull/1898 and now users need to source `pyenv init --path` on startup.
However, current `anyenv-init` does not contain this script so pyenv installed by anyenv no longer works unless you manually put  `pyenv init --path | source` in ~/.profile, config.fish, etc.

**Comment by aero** [comment]
anyenv is not maintained anymore?
should i switch to a different version manager?( asdf etc... )

**Comment by riywo** [comment]
v1.1.3 is released on master branch.

Homebrew update is waiting for this PR https://github.com/Homebrew/homebrew-core/pull/79241

**Comment by riywo** [comment]
Homebrew PR is merged.
